from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1138, 756)
        MainWindow.setStyleSheet("background-color: rgb(191, 191, 191);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.player1_label = QtWidgets.QLabel(self.centralwidget)
        self.player1_label.setGeometry(QtCore.QRect(456, 18, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.player1_label.setFont(font)
        self.player1_label.setObjectName("player1_label")
        self.player1_cards = QtWidgets.QFrame(self.centralwidget)
        self.player1_cards.setGeometry(QtCore.QRect(80, 50, 881, 161))
        self.player1_cards.setStyleSheet("border: 2px solid black;\n"
"border-color: rgb(25, 118, 210);\n"
"")
        self.player1_cards.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.player1_cards.setFrameShadow(QtWidgets.QFrame.Raised)
        self.player1_cards.setObjectName("player1_cards")
        self.player1_card1 = QtWidgets.QLabel(self.player1_cards)
        self.player1_card1.setGeometry(QtCore.QRect(40, 10, 111, 141))
        self.player1_card1.setText("")
        self.player1_card1.setScaledContents(True)
        self.player1_card1.setObjectName("player1_card1")
        self.player1_card2 = QtWidgets.QLabel(self.player1_cards)
        self.player1_card2.setGeometry(QtCore.QRect(210, 10, 111, 141))
        self.player1_card2.setText("")
        self.player1_card2.setScaledContents(True)
        self.player1_card2.setObjectName("player1_card2")
        self.player1_card3 = QtWidgets.QLabel(self.player1_cards)
        self.player1_card3.setGeometry(QtCore.QRect(380, 10, 111, 141))
        self.player1_card3.setText("")
        self.player1_card3.setScaledContents(True)
        self.player1_card3.setObjectName("player1_card3")
        self.player1_card4 = QtWidgets.QLabel(self.player1_cards)
        self.player1_card4.setGeometry(QtCore.QRect(550, 10, 111, 141))
        self.player1_card4.setText("")
        self.player1_card4.setScaledContents(True)
        self.player1_card4.setObjectName("player1_card4")
        self.player1_card5 = QtWidgets.QLabel(self.player1_cards)
        self.player1_card5.setGeometry(QtCore.QRect(720, 10, 111, 141))
        self.player1_card5.setText("")
        self.player1_card5.setScaledContents(True)
        self.player1_card5.setObjectName("player1_card5")
        self.player_frame = QtWidgets.QFrame(self.centralwidget)
        self.player_frame.setGeometry(QtCore.QRect(950, 229, 151, 302))
        self.player_frame.setStyleSheet("border: 2px solid black;\n"
"")
        self.player_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.player_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.player_frame.setObjectName("player_frame")
        self.player1_frame = QtWidgets.QLabel(self.player_frame)
        self.player1_frame.setGeometry(QtCore.QRect(40, 30, 71, 71))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.player1_frame.setFont(font)
        self.player1_frame.setStyleSheet("border: 1px solid black;\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"border-radius: 35px;\n"
"border-color: rgb(25, 118, 210);\n"
"")
        self.player1_frame.setAlignment(QtCore.Qt.AlignCenter)
        self.player1_frame.setObjectName("player1_frame")
        self.player2_frame = QtWidgets.QLabel(self.player_frame)
        self.player2_frame.setGeometry(QtCore.QRect(40, 194, 71, 71))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.player2_frame.setFont(font)
        self.player2_frame.setStyleSheet("border: 1px solid black;\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"border-radius: 35px;\n"
"border-color: rgb(198, 40, 40);")
        self.player2_frame.setAlignment(QtCore.Qt.AlignCenter)
        self.player2_frame.setObjectName("player2_frame")
        self.vs_label = QtWidgets.QLabel(self.player_frame)
        self.vs_label.setGeometry(QtCore.QRect(62, 125, 31, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        self.vs_label.setFont(font)
        self.vs_label.setStyleSheet("border: 0px solid black")
        self.vs_label.setObjectName("vs_label")
        self.player2_cards = QtWidgets.QFrame(self.centralwidget)
        self.player2_cards.setGeometry(QtCore.QRect(80, 570, 881, 161))
        self.player2_cards.setStyleSheet("border: 2px solid black;\n"
"border-color: rgb(198, 40, 40);\n"
"")
        self.player2_cards.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.player2_cards.setFrameShadow(QtWidgets.QFrame.Raised)
        self.player2_cards.setObjectName("player2_cards")
        self.player2_card1 = QtWidgets.QLabel(self.player2_cards)
        self.player2_card1.setGeometry(QtCore.QRect(40, 10, 111, 141))
        self.player2_card1.setText("")
        self.player2_card1.setScaledContents(True)
        self.player2_card1.setObjectName("player2_card1")
        self.player2_card2 = QtWidgets.QLabel(self.player2_cards)
        self.player2_card2.setGeometry(QtCore.QRect(210, 10, 111, 141))
        self.player2_card2.setText("")
        self.player2_card2.setScaledContents(True)
        self.player2_card2.setObjectName("player2_card2")
        self.player2_card3 = QtWidgets.QLabel(self.player2_cards)
        self.player2_card3.setGeometry(QtCore.QRect(380, 10, 111, 141))
        self.player2_card3.setText("")
        self.player2_card3.setScaledContents(True)
        self.player2_card3.setObjectName("player2_card3")
        self.player2_card4 = QtWidgets.QLabel(self.player2_cards)
        self.player2_card4.setGeometry(QtCore.QRect(550, 10, 111, 141))
        self.player2_card4.setText("")
        self.player2_card4.setScaledContents(True)
        self.player2_card4.setObjectName("player2_card4")
        self.player2_card5 = QtWidgets.QLabel(self.player2_cards)
        self.player2_card5.setGeometry(QtCore.QRect(720, 10, 111, 141))
        self.player2_card5.setText("")
        self.player2_card5.setScaledContents(True)
        self.player2_card5.setObjectName("player2_card5")
        self.player2_label = QtWidgets.QLabel(self.centralwidget)
        self.player2_label.setGeometry(QtCore.QRect(456, 538, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.player2_label.setFont(font)
        self.player2_label.setObjectName("player2_label")
        self.selected_card_frame1 = QtWidgets.QFrame(self.centralwidget)
        self.selected_card_frame1.setGeometry(QtCore.QRect(80, 229, 241, 302))
        self.selected_card_frame1.setStyleSheet("border: 2px solid black;\n"
"border-color: rgb(25, 118, 210);\n"
"")
        self.selected_card_frame1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.selected_card_frame1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.selected_card_frame1.setObjectName("selected_card_frame1")
        self.selected_card1 = QtWidgets.QLabel(self.selected_card_frame1)
        self.selected_card1.setGeometry(QtCore.QRect(60, 7, 111, 141))
        self.selected_card1.setStyleSheet("border-color: None;")
        self.selected_card1.setText("")
        self.selected_card1.setScaledContents(True)
        self.selected_card1.setObjectName("selected_card1")
        self.selected_card_frame2 = QtWidgets.QFrame(self.centralwidget)
        self.selected_card_frame2.setGeometry(QtCore.QRect(80, 380, 241, 151))
        self.selected_card_frame2.setStyleSheet("border: 2px solid black;\n"
"border-color: rgb(198, 40, 40);\n"
"")
        self.selected_card_frame2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.selected_card_frame2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.selected_card_frame2.setObjectName("selected_card_frame2")
        self.selected_card2 = QtWidgets.QLabel(self.selected_card_frame2)
        self.selected_card2.setGeometry(QtCore.QRect(60, 5, 111, 141))
        self.selected_card2.setStyleSheet("border-color: None;")
        self.selected_card2.setText("")
        self.selected_card2.setScaledContents(True)
        self.selected_card2.setObjectName("selected_card2")
        self.game_type = QtWidgets.QFrame(self.centralwidget)
        self.game_type.setGeometry(QtCore.QRect(374, 229, 531, 302))
        self.game_type.setStyleSheet("QFrame{\n"
"border: 2px solid black;\n"
"}")
        self.game_type.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.game_type.setFrameShadow(QtWidgets.QFrame.Raised)
        self.game_type.setObjectName("game_type")
        self.game_type_label = QtWidgets.QLabel(self.game_type)
        self.game_type_label.setGeometry(QtCore.QRect(10, 10, 281, 41))
        self.game_type_label.setStyleSheet("border: 0px solid black;\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.game_type_label.setObjectName("game_type_label")
        self.example_player = QtWidgets.QLabel(self.game_type)
        self.example_player.setGeometry(QtCore.QRect(20, 50, 181, 231))
        self.example_player.setStyleSheet("border: 0px solid black;")
        self.example_player.setText("")
        self.example_player.setScaledContents(True)
        self.example_player.setObjectName("example_player")
        self.example_pac = QtWidgets.QLabel(self.game_type)
        self.example_pac.setGeometry(QtCore.QRect(50, 212, 57, 16))
        self.example_pac.setStyleSheet("background-color: None;\n"
"border: 0px solid black;")
        self.example_pac.setText("")
        self.example_pac.setObjectName("example_pac")
        self.example_pas = QtWidgets.QLabel(self.game_type)
        self.example_pas.setGeometry(QtCore.QRect(50, 243, 57, 16))
        self.example_pas.setStyleSheet("background-color: None;\n"
"border: 0px;")
        self.example_pas.setText("")
        self.example_pas.setObjectName("example_pas")
        self.example_phy = QtWidgets.QLabel(self.game_type)
        self.example_phy.setGeometry(QtCore.QRect(113, 243, 57, 16))
        self.example_phy.setStyleSheet("background-color: None;\n"
"border: 0px;")
        self.example_phy.setText("")
        self.example_phy.setObjectName("example_phy")
        self.example_def = QtWidgets.QLabel(self.game_type)
        self.example_def.setGeometry(QtCore.QRect(113, 228, 57, 16))
        self.example_def.setStyleSheet("background-color: None;\n"
"border: 0px;")
        self.example_def.setText("")
        self.example_def.setObjectName("example_def")
        self.example_sho = QtWidgets.QLabel(self.game_type)
        self.example_sho.setGeometry(QtCore.QRect(50, 228, 57, 16))
        self.example_sho.setStyleSheet("background-color: None;\n"
"border: 0px;")
        self.example_sho.setText("")
        self.example_sho.setObjectName("example_sho")
        self.example_dri = QtWidgets.QLabel(self.game_type)
        self.example_dri.setGeometry(QtCore.QRect(113, 212, 57, 16))
        self.example_dri.setStyleSheet("background-color: None;\n"
"border: 0px;")
        self.example_dri.setText("")
        self.example_dri.setObjectName("example_dri")
        self.line = QtWidgets.QFrame(self.game_type)
        self.line.setGeometry(QtCore.QRect(290, 0, 3, 301))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.winner_label = QtWidgets.QLabel(self.game_type)
        self.winner_label.setGeometry(QtCore.QRect(300, 10, 221, 281))
        self.winner_label.setStyleSheet("font: 75 30pt \"MS Shell Dlg 2\";\n"
"border: 0px solid black\n"
"")
        self.winner_label.setObjectName("winner_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.player1_label.setText(_translate("MainWindow", "Player 1 Cards"))
        self.player1_frame.setText(_translate("MainWindow", "P1"))
        self.player2_frame.setText(_translate("MainWindow", "P2"))
        self.vs_label.setText(_translate("MainWindow", "VS"))
        self.player2_label.setText(_translate("MainWindow", "Player 2 Cards"))
        self.game_type_label.setText(_translate("MainWindow", "Stat Type:"))
        self.winner_label.setText(_translate("MainWindow", "Tie Game!"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
